{
 "title": "Central - Kubernetes Ingress Controller Dashboard",
 "description": "This Dashboard contains metrics visualization of Nginx Ingress Controller Running in Kubernetes Using Prometheus as Datasource.",
 "tags": [
  "central",
  "thanos"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "Thanos Querier" },
   {
    "name": "organization",
    "label": "Organization",
    "query": {
     "query": "label_values(kube_service_status_load_balancer_ingress, organization)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_service_status_load_balancer_ingress{organization=\"$organization\"}, cluster_name)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_service_status_load_balancer_ingress, namespace)"
    }
   },
   {
    "name": "ingress",
    "label": "Ingress",
    "query": {
     "query": "label_values(kube_service_status_load_balancer_ingress{namespace=~\"$namespace\"}, ingress) "
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Controller Request Volume",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "round(sum(irate(nginx_ingress_controller_requests{organization=~\"$organization\",cluster_name=~\"$cluster\",namespace=~\"$namespace\"}[$__range])), 0.001)"
    }
   ]
  },
  {
   "title": "Controller Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(nginx_ingress_controller_nginx_process_connections{organization=~\"$organization\",cluster_name=~\"$cluster\",controller_namespace=~\"$namespace\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Controller Success Rate (non-4|5xx responses)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{organization=~\"$organization\",cluster_name=~\"$cluster\",namespace=~\"$namespace\",status!~\"[4-5].*\"}[$__range])) / sum(rate(nginx_ingress_controller_requests{organization=~\"$organization\",cluster_name=~\"$cluster\",namespace=~\"$namespace\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Config Reloads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "avg(irate(nginx_ingress_controller_success{organization=~\"$organization\",cluster_name=~\"$cluster\",controller_namespace=~\"$namespace\"}[$__range])) * 60"
    }
   ]
  },
  {
   "title": "Last Config Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(nginx_ingress_controller_config_last_reload_successful{organization=~\"$organization\",cluster_name=~\"$cluster\"} == 0)"
    }
   ]
  },
  {
   "title": "Ingress Request Volume",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(nginx_ingress_controller_requests{organization=~\"$organization\",cluster_name=~\"$cluster\",controller_namespace=~\"$namespace\",ingress=~\"$ingress\"}[$__range])) by (ingress), 0.001)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "Ingress Success Rate (non-4|5xx responses)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{organization=~\"$organization\",cluster_name=~\"$cluster\",namespace=~\"$namespace\",ingress=~\"$ingress\",status!~\"[4-5].*\"}[2m])) by (ingress) / sum(rate(nginx_ingress_controller_requests{organization=~\"$organization\",cluster_name=~\"$cluster\",namespace=~\"$namespace\",ingress=~\"$ingress\"}[2m])) by (ingress)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "Ingress Percentile Response Times and Transfer Rates",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{organization=~\"$organization\",cluster_name=~\"$cluster\",ingress!=\"\",controller_namespace=~\"$namespace\",ingress=~\"$ingress\"}[$__range])) by (le, ingress))",
     "legendFormat": "{{ ingress }}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{organization=~\"$organization\",cluster_name=~\"$cluster\",ingress!=\"\",controller_namespace=~\"$namespace\",ingress=~\"$ingress\"}[$__range])) by (le, ingress))",
     "legendFormat": "{{ ingress }}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{organization=~\"$organization\",cluster_name=~\"$cluster\",ingress!=\"\",controller_namespace=~\"$namespace\",ingress=~\"$ingress\"}[$__range])) by (le, ingress))",
     "legendFormat": "{{ destination_service }}"
    },
    {
     "expr": "sum(irate(nginx_ingress_controller_request_size_sum{organization=~\"$organization\",cluster_name=~\"$cluster\",ingress!=\"\",controller_namespace=~\"$namespace\",ingress=~\"$ingress\"}[$__range])) by (ingress)",
     "legendFormat": "{{ ingress }}"
    },
    {
     "expr": "sum(irate(nginx_ingress_controller_response_size_sum{organization=~\"$organization\",cluster_name=~\"$cluster\",ingress!=\"\",controller_namespace=~\"$namespace\",ingress=~\"$ingress\"}[$__range])) by (ingress)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "Network I/O pressure",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (irate (nginx_ingress_controller_request_size_sum{organization=~\"$organization\",cluster_name=~\"$cluster\",controller_namespace=~\"$namespace\"}[2m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (irate (nginx_ingress_controller_response_size_sum{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\"}[2m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(nginx_ingress_controller_nginx_process_resident_memory_bytes{organization=~\"$organization\",cluster_name=~\"$cluster\",controller_namespace=~\"$namespace\"}) ",
     "legendFormat": "nginx"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (nginx_ingress_controller_nginx_process_cpu_seconds_total{organization=~\"$organization\",cluster_name=~\"$cluster\",controller_namespace=~\"$namespace\"}[2m])) ",
     "legendFormat": "nginx"
    }
   ]
  }
 ]
}