{
 "title": "Hubble",
 "tags": [
  "hubble",
  "features",
  "image service"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Running Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\",pod=~\"hubble-.*\", pod!~\"hubble-ingress.*\"})"
    }
   ]
  },
  {
   "title": "Pending Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Pending\",pod=~\"hubble-.*\", pod!~\"hubble-ingress.*\"})"
    }
   ]
  },
  {
   "title": "Failed Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Failed\",pod=~\"hubble-.*\", pod!~\"hubble-ingress.*\"})"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod_name=~\"hubble-.*\", pod!~\"hubble-ingress.*\"}[1m]))",
     "legendFormat": "received"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod_name=~\"hubble-.*\", pod!~\"hubble-ingress.*\"}[1m]))",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(container_memory_working_set_bytes{pod=~\"hubble-.*\", pod!~\"hubble-ingress.*\", kubernetes_namespace=\"hubble\"})",
     "legendFormat": "Current"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_memory_bytes{pod=~\"hubble-.*\", pod!~\"hubble-ingress.*\", kubernetes_namespace=\"hubble\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_memory_bytes{pod=~\"hubble-.*\", pod!~\"hubble-ingress.*\", kubernetes_namespace=\"hubble\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{pod=~\"hubble-.*\", pod!~\"hubble-ingress.*\"}[1m]))",
     "legendFormat": "Current"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_cpu_cores{pod=~\"hubble-.*\", pod!~\"hubble-ingress.*\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_cpu_cores{pod=~\"hubble-.*\", pod!~\"hubble-ingress.*\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "avg(rate(container_cpu_cfs_throttled_seconds_total{pod=~\"hubble-.*\", pod!~\"hubble-ingress.*\"}[1m]))",
     "legendFormat": "Throttled"
    }
   ]
  },
  {
   "title": "Node JS Breakdown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Eventloop Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "hubble_nodejs_eventloop_lag_seconds",
     "legendFormat": "last"
    },
    {
     "expr": "hubble_nodejs_eventloop_lag_p99_seconds",
     "legendFormat": "p99"
    },
    {
     "expr": "hubble_nodejs_eventloop_lag_p50_seconds",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Process Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "hubble_process_virtual_memory_bytes",
     "legendFormat": "virtual memory"
    },
    { "expr": "hubble_process_heap_bytes", "legendFormat": "heap memory" }
   ]
  },
  {
   "title": "Active Handlers/Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hubble_nodejs_active_handles_total",
     "legendFormat": "Active Handler"
    },
    {
     "expr": "hubble_nodejs_active_requests_total",
     "legendFormat": "Active Request"
    }
   ]
  },
  {
   "title": "Rate of CPU Time Spent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(hubble_process_cpu_seconds_total[10m])",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Rate of Garbage Collection Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(hubble_nodejs_gc_duration_seconds_sum[10m])",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Used File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "( hubble_process_open_fds / hubble_process_max_fds)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Garbage Collection Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "hubble_nodejs_gc_duration_seconds_sum",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Rate of Garbage Collection",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(hubble_nodejs_gc_duration_seconds_count[10m])",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Heap Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "hubble_nodejs_heap_size_total_bytes",
     "legendFormat": "total"
    },
    {
     "expr": "hubble_nodejs_heap_size_used_bytes",
     "legendFormat": "used"
    },
    {
     "expr": "hubble_process_resident_memory_bytes",
     "legendFormat": "resident"
    },
    {
     "expr": "hubble_nodejs_external_memory_bytes",
     "legendFormat": "external"
    }
   ]
  },
  {
   "title": "Garbage Collection Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hubble_nodejs_gc_duration_seconds_count",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Heap Space Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "hubble_nodejs_heap_space_size_used_bytes",
     "legendFormat": "{{space}}"
    }
   ]
  }
 ]
}