{
 "title": "Request by Referer",
 "description": "shows requests aggregated by referer.  Can be used to isolate request to a site",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "site",
    "label": "Site",
    "query": "www.homebase.co.uk, www.movementumuk.com, www.myprotein.com, checkout.myprotein.com, www.zavvi.com"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (http_referer)(count_over_time({app=\"nginx-ingress-controller\"} != `GET /images/healthcheck` | regexp `(?P<remote_addr>((?:[0-9]{1,3}\\.){3}[0-9]{1,3})) (?P<dash>\\S+) (?P<remote_user>\\S+) \\[(?P<time_local>[\\w:\\/]+\\s[+|-]\\d{4})\\] \\\"(?P<request>\\S+)\\s?(?P<path>\\S+)?\\s?(?P<protocol>\\S+)?\\\" (?P<status_code>\\d{3}|-) (?P<body_bytes_sent>\\d+|-)\\s?\\\"[a-z]*://(?P<http_referer>[^\\/]*)(?P<http_referer_path>[^\\\"]*)` | status_code = `200` [$__interval])) "
    }
   ]
  },
  {
   "title": "Non Success Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (http_referer)(count_over_time({app=\"nginx-ingress-controller\"} != `GET /images/healthcheck` | regexp `(?P<remote_addr>((?:[0-9]{1,3}\\.){3}[0-9]{1,3})) (?P<dash>\\S+) (?P<remote_user>\\S+) \\[(?P<time_local>[\\w:\\/]+\\s[+|-]\\d{4})\\] \\\"(?P<request>\\S+)\\s?(?P<path>\\S+)?\\s?(?P<protocol>\\S+)?\\\" (?P<status_code>\\d{3}|-) (?P<body_bytes_sent>\\d+|-)\\s?\\\"[a-z]*://(?P<http_referer>[^\\/]*)(?P<http_referer_path>[^\\\"]*)` | status_code != `200` [$__interval])) "
    }
   ]
  },
  { "title": "${site}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "site" },
  {
   "title": "Pages with Success",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (http_referer_path)(count_over_time({app=\"nginx-ingress-controller\"} != `GET /images/healthcheck` | regexp `(?P<remote_addr>((?:[0-9]{1,3}\\.){3}[0-9]{1,3})) (?P<dash>\\S+) (?P<remote_user>\\S+) \\[(?P<time_local>[\\w:\\/]+\\s[+|-]\\d{4})\\] \\\"(?P<request>\\S+)\\s?(?P<path>\\S+)?\\s?(?P<protocol>\\S+)?\\\" (?P<status_code>\\d{3}|-) (?P<body_bytes_sent>\\d+|-)\\s?\\\"[a-z]*://(?P<http_referer>[^\\/]*)(?P<http_referer_path>[^\\\"]*)` | status_code = `200` |~ \"${site}\" [$__range])) "
    }
   ]
  },
  {
   "title": "Pages with Fail",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 8, "x": 7, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (http_referer_path)(count_over_time({app=\"nginx-ingress-controller\"} != `GET /images/healthcheck` | regexp `(?P<remote_addr>((?:[0-9]{1,3}\\.){3}[0-9]{1,3})) (?P<dash>\\S+) (?P<remote_user>\\S+) \\[(?P<time_local>[\\w:\\/]+\\s[+|-]\\d{4})\\] \\\"(?P<request>\\S+)\\s?(?P<path>\\S+)?\\s?(?P<protocol>\\S+)?\\\" (?P<status_code>\\d{3}|-) (?P<body_bytes_sent>\\d+|-)\\s?\\\"[a-z]*://(?P<http_referer>[^\\/]*)(?P<http_referer_path>[^\\\"]*)` | status_code != `200` |~ \"${site}\" [$__range])) "
    }
   ]
  },
  {
   "title": "Failed Image",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 9, "x": 15, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (path)(count_over_time({app=\"nginx-ingress-controller\"} != `GET /images/healthcheck` | regexp `(?P<remote_addr>((?:[0-9]{1,3}\\.){3}[0-9]{1,3})) (?P<dash>\\S+) (?P<remote_user>\\S+) \\[(?P<time_local>[\\w:\\/]+\\s[+|-]\\d{4})\\] \\\"(?P<request>\\S+)\\s?(?P<path>\\S+)?\\s?(?P<protocol>\\S+)?\\\" (?P<status_code>\\d{3}|-) (?P<body_bytes_sent>\\d+|-)\\s?\\\"[a-z]*://(?P<http_referer>[^\\/]*)(?P<http_referer_path>[^\\\"]*)` | status_code != `200` |~ \"${site}\" [$__range])) "
    }
   ]
  },
  {
   "title": "Failed Logs",
   "type": "logs",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "{app=\"nginx-ingress-controller\"} \n    != `GET /images/healthcheck` \n    | pattern `<ip> - - [<date>] \"<_> <request> <_>\" <status> <size> \"<referer>\" \"<agent>\" <_>`  | status != \"200\"\n    |~ \"${site}\" "
    }
   ]
  }
 ]
}