{
 "title": "Request by Referer",
 "description": "shows requests aggregated by referer.  Can be used to isolate request to a site",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (http_referer)(count_over_time({app=\"nginx-ingress-controller\"} != `GET /images/healthcheck` | regexp `(?P<remote_addr>((?:[0-9]{1,3}\\.){3}[0-9]{1,3})) (?P<dash>\\S+) (?P<remote_user>\\S+) \\[(?P<time_local>[\\w:\\/]+\\s[+|-]\\d{4})\\] \\\"(?P<request>\\S+)\\s?(?P<path>\\S+)?\\s?(?P<protocol>\\S+)?\\\" (?P<status_code>\\d{3}|-) (?P<body_bytes_sent>\\d+|-)\\s?\\\"[a-z]*://(?P<http_referer>[^\\/]*)(?P<http_referer_path>[^\\\"]*)` | status_code = `200` [$__interval])) "
    }
   ]
  },
  {
   "title": "Non Success Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (http_referer)(count_over_time({app=\"nginx-ingress-controller\"} != `GET /images/healthcheck` | regexp `(?P<remote_addr>((?:[0-9]{1,3}\\.){3}[0-9]{1,3})) (?P<dash>\\S+) (?P<remote_user>\\S+) \\[(?P<time_local>[\\w:\\/]+\\s[+|-]\\d{4})\\] \\\"(?P<request>\\S+)\\s?(?P<path>\\S+)?\\s?(?P<protocol>\\S+)?\\\" (?P<status_code>\\d{3}|-) (?P<body_bytes_sent>\\d+|-)\\s?\\\"[a-z]*://(?P<http_referer>[^\\/]*)(?P<http_referer_path>[^\\\"]*)` | status_code != \"200\" and status_code != \"204\" [$__interval])) "
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "site" },
  {
   "title": "Failed Logs",
   "type": "logs",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{app=\"nginx-ingress-controller\"} \n    != `GET /images/healthcheck` \n    | pattern `<ip> - - [<date>] \"<_> <request> <_>\" <status> <size> \"<referer>\" \"<agent>\" <_>`  | status != \"200\" and status != \"204\""
    }
   ]
  }
 ]
}